### ISSUE TITLE
Perhaps tag a release?

### ISSUE THREAD

**Issue by mdorman** [jplindstrom/emacs-org-transform-tree-table#2]
I've found this occasionally useful---so thanks for developing it!---and was wondering if it might not make sense to tag a release so that melpa-stable will pick it up?

**Comment by jplindstrom** [comment]
Sorry, didn't see this until now :/

Could you point me to what I need to do? Or is it just creating a tag on master with "1.0.0" or something?

**Comment by mdorman** [comment]
All you need to do is make a tag, and the existing melpa recipe will be applied to generate an appropriate numbered release for melpa-stable.

**Comment by jplindstrom** [comment]
Ok, I've done this now.
