### ISSUE TITLE
Wrong number of arguments error

### ISSUE THREAD

**Issue by coyotespike** [jplindstrom/emacs-org-transform-tree-table#4]
Thanks for making this package!

I'm using helm spacemacs. When I copy your example table:

```
| Heading          | Login | Access | Color | Cost | COLUMNS                            |
| * Pages          |       |        |       |      | %30ITEM %10Login %10Access %10Cost |
| ** About         | No    | All    |       |      |                                    |
| ** Products      | No    | All    |       |      | %30ITEM %10Color                   |
| *** Free Widget  | Yes   | All    | Green |      |                                    |
|     This one is: |       |        |       |      |                                    |
|     - Awesome    |       |        |       |      |                                    |
|     - Green      |       |        |       |      |                                    |
| *** Paid Thingy  | Yes   | Paid   | Blue  |   30 |                                    |
```
then I can call `org-transform-table/org-tree-buffer-from-org-table`, and the example outline is generated.

However, when I copy and paste the example outline, I cannot generate a table, and I have the same problem with another outline I've made.

I get `helm-M-x: Wrong number of arguments: (0 . 2), 3`.

Seems odd that it will work on a table, but not on an outline.

Thanks for any ideas!

**Comment by coyotespike** [comment]
Apparently this message means that the function expects at least 0 and up to 2 arguments, but instead got 3 arguments.

**Comment by coyotespike** [comment]
In the meantime, `C-c C-x i` will insert a table from column view in the same outline. So we can still export with more-or-less the same concepts.

**Comment by Gurras** [comment]
Running 
Aquamacs 3.3  GNU Emacs 25.1.1
and
Org mode version 9.0.9,

I was able to fix this issue (and another problem) with these edits:

(defun ott/org-tree/current-property-values-from-keys (property-keys)
  "Return list of values (possibly nil) for each property in PROPERTY-KEYS."
  (mapcar
   (lambda (key)
     (assoc-default key (org-entry-properties nil 'standard))) 
     ;WAS: (assoc-default key (org-entry-properties nil 'standard key))) 
   property-keys))

(defun ott/org-tree/heading-text ()
  "Return the text contents of the current heading (the text beneath the '* Heading' itself), or '' if there isn't one."
  (org-end-of-meta-data t) 
  ;WAS: (org-end-of-meta-data-and-drawers)
  ;; include leading empty lines
  (while (looking-back "[\n ]+\n")
    (backward-char)
    (beginning-of-line))

  (let* ((beg (point))
         (end (if (org-at-heading-p)
                  (point)
                  (save-excursion (outline-next-heading) (point))))
         )
    (buffer-substring-no-properties beg end)
    )
  )

**Comment by Gurras** [comment]
Running
Aquamacs 3.3 GNU Emacs 25.1.1
and
Org mode version 9.0.9,

I was able to fix this issue (and another problem) with these edits:

```
(defun ott/org-tree/current-property-values-from-keys (property-keys)
  "Return list of values (possibly nil) for each property in PROPERTY-KEYS."
  (mapcar
   (lambda (key)
     (assoc-default key (org-entry-properties nil 'standard))) 
     ;WAS: (assoc-default key (org-entry-properties nil 'standard key))) 
   property-keys))

(defun ott/org-tree/heading-text ()
  "Return the text contents of the current heading (the text beneath the '* Heading' itself), or '' if there isn't one."
  (org-end-of-meta-data t) 
  ;WAS: (org-end-of-meta-data-and-drawers)
  ;; include leading empty lines
  (while (looking-back "[\n ]+\n")
    (backward-char)
    (beginning-of-line))

  (let* ((beg (point))
         (end (if (org-at-heading-p)
                  (point)
                  (save-excursion (outline-next-heading) (point))))
         )
    (buffer-substring-no-properties beg end)
    )
  )


```

**Comment by mohammadanton** [comment]
> Running
> Aquamacs 3.3 GNU Emacs 25.1.1
> and
> Org mode version 9.0.9,
> 
> I was able to fix this issue (and another problem) with these edits:
> 
> ```
> (defun ott/org-tree/current-property-values-from-keys (property-keys)
>   "Return list of values (possibly nil) for each property in PROPERTY-KEYS."
>   (mapcar
>    (lambda (key)
>      (assoc-default key (org-entry-properties nil 'standard))) 
>      ;WAS: (assoc-default key (org-entry-properties nil 'standard key))) 
>    property-keys))
> 
> (defun ott/org-tree/heading-text ()
>   "Return the text contents of the current heading (the text beneath the '* Heading' itself), or '' if there isn't one."
>   (org-end-of-meta-data t) 
>   ;WAS: (org-end-of-meta-data-and-drawers)
>   ;; include leading empty lines
>   (while (looking-back "[\n ]+\n")
>     (backward-char)
>     (beginning-of-line))
> 
>   (let* ((beg (point))
>          (end (if (org-at-heading-p)
>                   (point)
>                   (save-excursion (outline-next-heading) (point))))
>          )
>     (buffer-substring-no-properties beg end)
>     )
>   )
> ```

Thanks, this is working

**Comment by Jonta** [comment]
@mohammadanton Is it still working for you?

If so: org- and emacs-versions?

**Comment by mohammadanton** [comment]
> @mohammadanton Is it still working for you?
> 
> If so: org- and emacs-versions?

I didn't use it anymore, I think it still working.

**Comment by Jonta** [comment]
@mohammadanton Thanks for the reply. Do you recall which org- and emacs-versions this last worked with for you?

@Gurras & @jplindstrom If you're still around, I'd like your input. =)

**Comment by Gurras** [comment]
Unfortunately, I can't find where I used this a couple of years ago, and haven't used since.


________________________________
Från: Jonta <notifications@github.com>
Skickat: den 1 april 2020 16:42:24
Till: jplindstrom/emacs-org-transform-tree-table
Kopia: Gunnar Eriksson; Mention
Ämne: Re: [jplindstrom/emacs-org-transform-tree-table] Wrong number of arguments error (#4)


@mohammadanton<https://github.com/mohammadanton> Thanks for the reply. Do you recall which org- and emacs-versions this last worked with for you?

@Gurras<https://github.com/Gurras> & @jplindstrom<https://github.com/jplindstrom> If you're still around, I'd like your input. =)

**Comment by jplindstrom** [comment]
Hi guys, sorry for being absent for so long.
I've fixed these things now, so if you're still interested please try again. It's on melpa now. 
Tested with Emacs 25 and latest org mode.

**Comment by Jonta** [comment]
Hooray!

Thank you. I already had grand plans to accelerate my elisp-learning and everything

Works in GNU Emacs 26.3, org 9.3.6
